adds more operationlized terraform
dod-ccpo/atst pull request #1727
Opened 2020-08-12 14:54 UTC by mikepw

2020-08-12 17:01 UTC, dandds commented on terraform/modules/azure_ad/ad_application.tf
> +  end_date             = "2099-01-01T01:02:03Z"
Do we have to provide values for `end_date`? Does it default to something reasonable if we don't?

2020-08-12 17:08 UTC, dandds commented on terraform/modules/k8s-private/main.tf
> -}
Can you fill me in on why we're dropping all this networking stuff for the private cluster?

2020-08-12 17:11 UTC, dandds commented on terraform/modules/k8s/main.tf
> -}
Don't we need this for logging from the cluster?

2020-08-12 17:13 UTC, dandds commented on terraform/modules/k8s/variables.tf
> +variable "client_object_id" {}
I think the types/descriptions are nice, but up to you.

2020-08-12 17:13 UTC, dandds commented on terraform/modules/keyvault/main.tf
> -}
Same question as with the k8s cluster: isn't this what points the logs into our LA Workspace?

2020-08-12 17:20 UTC, dandds commented on terraform/providers/dryrun2/private-k8s.tasdf
> +}
What's the extension on this? 🤔

2020-08-12 17:23 UTC, dandds commented on deploy/overlays/cloudzero-dryrun-staging/envvars.yml
> +  REDIS_HOST: cloudzero-dryrun2-redis.redis.cache.windows.net:6380 # TODO(heyzoos) Parameterize from terraform!
I don't think we should be changing this overlay if we're also adding a new overlay for dryrun2. We'll still need the old value here to manage the dryrun environment.

2020-08-12 17:31 UTC, dandds commented on deploy/overlays/cloudzero-pwdev-dryrun2/autoscaling.yml
> +  maxReplicas: 2
The filename pattern I've used in the past for these is "cloudzero-[infra environment name]-[k8s namespace name]", which would make this clouzero-dryrun2-staging. "pwdev" is our original infra environment, so it doesn't really correspond to anything anymore.

2020-08-12 17:52 UTC, mikepw commented on terraform/modules/azure_ad/ad_application.tf
> +  end_date             = "2099-01-01T01:02:03Z"
an `end_date` must be specified.. and I'm not seeing a default. (https://www.terraform.io/docs/providers/azuread/r/service_principal_password.html)

2020-08-12 17:58 UTC, mikepw commented on deploy/overlays/cloudzero-pwdev-dryrun2/autoscaling.yml
> +  maxReplicas: 2
agree.. I think this is @jesse-dds change and mistakenly made it into the world.  I want to remove environment specific working overlays and instead go towards generating 'reference overlays' which would eliminate the need for multiple working directories of k8s config..

2020-08-12 17:58 UTC, mikepw commented on deploy/overlays/cloudzero-dryrun-staging/envvars.yml
> +  REDIS_HOST: cloudzero-dryrun2-redis.redis.cache.windows.net:6380 # TODO(heyzoos) Parameterize from terraform!
agree. @jesse-dds can you change back?

2020-08-12 17:59 UTC, mikepw commented on terraform/providers/dryrun2/private-k8s.tasdf
> +}
haha loving that WIP label rn..

2020-08-12 18:15 UTC, mikepw commented on deploy/azure/crls-sync.yaml
> +  schedule: "29 * * * *"
done

2020-08-12 18:24 UTC, mikepw commented on pyproject.toml
> +openshift = "^0.11.2"
done

2020-08-12 18:28 UTC, dandds commented on terraform/modules/azure_ad/ad_application.tf
> +  end_date             = "2099-01-01T01:02:03Z"
The docs say it's optional; there's also `end_date_relative`, which might suit us better.

2020-08-12 20:07 UTC, mikepw commented on terraform/modules/k8s/main.tf
> -}
we ran into a real issue that this log workspace already existed causing applies to fail.  It was very very strange.  I removed it to alleviate and alas the logs were still there.  I will re-run with this included to make sure we get what we need out of logging.

2020-08-12 20:15 UTC, mikepw commented on terraform/modules/azure_ad/ad_application.tf
> +  end_date             = "2099-01-01T01:02:03Z"
one or the other must be specified is what I should've said. If someone were to read an `end_date_relative` that is not familiar with the date/time of deployment they might be guessing when this service principal password expires.

2020-08-12 20:20 UTC, mikepw commented on terraform/modules/k8s-private/main.tf
> -}
I will test again but I'm fairly certain that the extra networking was superfluous when the AKS Cluster becomes private. The gateway was for egress only access but since we'll need a route to the internet for ingress connections to AKS Cluster endpoints I think that doesn't make sense anymore.

2020-08-19 19:00 UTC, carleton-dds commented on ansible/roles/azure_keyvault/tasks/secret.yml
> +
What's with all the blank lines in this file? Also is this valid ansible YML? looks like you got a lot of shell commands too

2020-08-24 19:59 UTC, carleton-dds commented on terraform/providers/dryrun3/bastion.tfasdf
> +
What's with the file extension on this?

2020-08-27 18:52 UTC, jesse-dds commented on ansible/roles/terraform/tasks/setup.yml
> +  register: tf_run
Potentially no longer necessary since we re-register the outputs in "show_outputs.yml"

2020-08-27 18:54 UTC, jesse-dds commented
Could we rename all of the "show_outputs.yml" files to "register_outputs.yml" to better match what they actually do?

2020-08-27 19:04 UTC, tomdds commented on ansible/databases.yml
> +        db_init_details: "{{ tf_app_env_outputs.outputs }}"
Does `db_init_details` need to go away since it's not used in `postgres.yml` in lieu of directly referencing `tf_app_env_outputs`?

2020-08-27 19:11 UTC, jesse-dds commented on ansible/roles/db/tasks/postgres.yml
> +      tenant: "{{ lookup('env','SUBSCRIPTION_TENANT')}}"
We need to make sure we enable the GUID extension here since we're not running the .py script any longer

2020-08-27 19:11 UTC, tomdds commented on ansible/roles/db/tasks/postgres.yml
> +      tenant: "{{ lookup('env','SUBSCRIPTION_TENANT')}}"
What do we need to ensure the "uuid-ossp" extension is enabled in the database and done in `script/create_database.py`

2020-08-27 19:12 UTC, tomdds commented on ansible/roles/db/tasks/postgres.yml
> +      tenant: "{{ lookup('env','SUBSCRIPTION_TENANT')}}"
```
conn.execute(f'CREATE EXTENSION IF NOT EXISTS "{extension_name}";')
```

2020-08-27 19:15 UTC, tomdds commented on ansible/roles/db/tasks/postgres.yml
> +      tenant: "{{ lookup('env','SUBSCRIPTION_TENANT')}}"
Can we use this with azure's hosted postgres? https://docs.ansible.com/ansible/2.4/postgresql_ext_module.html

2020-08-27 19:19 UTC, tomdds commented on ansible/roles/db/tasks/postgres.yml
> +        ATAT_PGPASSWORD: "{{  tf_app_env_outputs.atat_user_password.value  }}"
Branches from the dryrun doc, can't connect using atat user creds here, but dryrun dock specifies they should be used for this.

2020-09-21 17:28 UTC, carleton-dds commented on ansible/.gitignore
> +**/*.sh
Why is there a second .gitignore? you should be able to put all this in the root one

2020-09-22 15:52 UTC, dandds requested changes
Happy to help poke into whatever the problem is, but I think there has to be a better solution than removing the application's lockfile.

2020-09-22 15:52 UTC, dandds commented on poetry.lock
> -[[package]]
Wait, why are we removing the lockfile? Without a lockfile, we'll have a much harder time creating reproducible builds.

2020-09-22 17:25 UTC, dandds approved these changes
🎉

2020-09-22 17:27 UTC, jesse-dds approved these changes

2020-09-22 17:36 UTC, carleton-dds approved these changes

2020-09-22 18:15 UTC, tomdds approved these changes
:shipit:

2020-09-22 18:43 UTC, merged