put params at top of circle ci config so they're accessible via api
dod-ccpo/atst pull request #1772
Opened 2020-09-03 19:44 UTC by mikepw

I scoped the original parameters too deep these bring them up to the top level as per circle ci docs:

https://circleci.com/docs/2.0/pipeline-variables/

2020-09-03 20:58 UTC, tomdds requested changes
2 small changes, otherwise 🎉 parameterization!

2020-09-03 20:58 UTC, tomdds commented on .circleci/config.yml
> +            kubectl set image cronjobs.batch/crls crls=<< pipeline.parameters.tag >> --namespace=<< pipeline.parameters.namespace >>
You're still referencing the global `pipeline` scope for the `tag` and `namespace` params, which should be local

2020-09-03 20:58 UTC, tomdds commented on .circleci/config.yml
> +        default: << pipeline.parameters.tag >>
Seeing this makes me think it might be worth it to do this for all of the other params you migrated to the pipeline. That way each command/job will have all it's potential params documented in one place rather than throughout it's body. Thoughts?

2020-09-08 20:09 UTC, mikepw commented on .circleci/config.yml
> +        default: << pipeline.parameters.tag >>
just seeing this Tom! yea I agree. For dry run we're start w/ what's in here then iterate.

2020-09-08 20:09 UTC, jesse-dds approved these changes

2020-09-09 20:06 UTC, tomdds approved these changes

2020-09-15 18:23 UTC, merged