[AT-5435] EIFS Federated Authentication
dod-ccpo/atst pull request #1789
Opened 2020-09-10 21:11 UTC by tomdds

Follow on from https://github.com/dod-ccpo/atst/pull/1694 to introduce SAML authentication as the primary login mechanism. Closes a majority of https://ccpo.atlassian.net/browse/AT-5435, except removing the original authentication (taken care of in https://github.com/dod-ccpo/atst/pull/1773 and https://github.com/dod-ccpo/atst/pull/1774).

While this makes some changes to the `login-dev` implementation, that will still remain available for testing as either saml only or with basic auth.

Work completed in collaboration with @carleton-dds and @okaycj-atat 

# Testing Procedure

### Setup

**Note:** In order to log in against the EIFS SAML provider, you will need to be able to authenticate via CAC. This requires a card, a card reader, and the correct cert chain installed on your device.

**Environment**
The 1password vault contains the updated configuration names and values under the entry `SAML Identity Provider Local Config`. You'll need to place these entries in the relevant config file (likely dev.ini)

You'll also need [ngrok](https://ngrok.com/) to forward your local server to a public domain. You can find the ngrok auth token in 1password as `ngrok auth token`. To set up the local development tunnel, you need to run the following commands:
```
ngrok authtoken <insert token here>
ngrok http -subdomain=atat-local https://localhost:8000
```

**Certs**
The EIFS SAML identity provider requires that we run a secure server, which is provided by ngrok, but that also needs to relay to a local secure server.

First, generate some self-signed certs with `script/create_local_certs`

Then run a secure version of the dev environment with `script/secure_server`

### Testing
If you have everything set up as prescribed above, you should be able to visit `https://atat-local.ngrok.io` and see your local instance running. Once you visit that, you can either click through the `Sign in with CAC` button and modal, or visit `https://atat-local.ngrok.io/login` and you will be redirected to EIFS to select your CAC cert and enter your pin. When you return to ATAT, you'll either be on your home page or at the user creation screen (if this is your first login).

2020-09-14 19:51 UTC, dandds requested changes
One small cleanup change and a question. Looks great!

2020-09-14 19:51 UTC, dandds commented on atat/routes/dev.py
> +def get_or_create_persona(persona):
You and I added essentially the same helper function to this file in different places. You can remove one or the other and make sure they're used in the correct places. The other is called `get_or_create_dev_user` on line 115.

2020-09-14 19:51 UTC, dandds commented on pyproject.toml
> +cachetools = "^4.1.1"
Are you pulling this in for specific functionality, like the expiry?

2020-09-14 21:00 UTC, tomdds commented on pyproject.toml
> +cachetools = "^4.1.1"
Yeah, specifically for `@cachetools.func.ttl_cache` which is a "time to live" cache. The python std lib only gives you lru cache (least recently used).

2020-09-14 21:31 UTC, tomdds commented on atat/routes/dev.py
> +def get_or_create_persona(persona):
Ah, yep, removed duplication in my latest rebase

2020-09-15 11:54 UTC, dandds requested changes
Looks like `SAML_LOGIN_DEV` got re-introduced by the rebase. I might compare the `login_dev` function against the staging branch and see if any other small changes are missing.

2020-09-15 11:54 UTC, dandds commented on atat/routes/dev.py
> +    ) and request.method == "GET":
I removed the `SAML_LOGIN_DEV` setting on #1777 , so I think you can remove it from this branch. This line should just check the `request.method` since `/login-dev` is only used with fed auth now.

2020-09-15 11:54 UTC, dandds commented on config/base.ini
> +SAML_LOGIN_DEV = False
You can drop this.

2020-09-15 14:06 UTC, tomdds commented on atat/routes/dev.py
> +    ) and request.method == "GET":
Ah yep, didn't catch this during rebase

2020-09-15 14:46 UTC, dandds commented on deploy/overlays/cloudzero-dryrun-master/envvars.yml
> +  SAML_LOGIN_DEV: "true"
Nitpicky, sorry, but there's one more leftover.

2020-09-15 14:47 UTC, dandds approved these changes
There's one more instance of SAML_LOGIN_DEV. I approve anticipating that getting dropped! Nice work all!

2020-09-15 14:59 UTC, graham-dds reviewed
Just a few smallish comments.

One thing I noticed throughout: since #1643 we're trying to consistently use `printf` style interpolation in logging messages. Is that something that we should use throughout the new logging that that's introduced in this PR?

2020-09-15 14:59 UTC, graham-dds commented on tests/routes/test_saml_helpers.py
> +    mock_saml_auth.return_value = mock_auth
Do you think we could somehow package some of this mock auth setup into a fixture? It's a lot of mocking to set up each time it's used. Because it we need to control some of the inner return values though, maybe we could provide parameters to the fixtures with one of the methods outlined [here](https://github.com/pytest-dev/pytest/issues/2502#issuecomment-308403299).

Also, another thing that could make this a little more streamlined is to use [`configure_mock`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.configure_mock) to set those nested return values.

2020-09-15 18:30 UTC, tomdds commented on tests/routes/test_saml_helpers.py
> +    mock_saml_auth.return_value = mock_auth
Good call https://github.com/dod-ccpo/atst/pull/1789/commits/9c54977de5557d7440a290173604b6e4e94eb679

2020-09-15 18:30 UTC, tomdds commented on tests/routes/test_saml_helpers.py
> +def test_get_user_from_saml_attributes():
bundled them all together with a fixture https://github.com/dod-ccpo/atst/pull/1789/commits/94442e83efb4963d7042755b1faffdb0724fc4b4

2020-09-15 18:31 UTC, tomdds commented on atat/routes/__init__.py
> +@bp.route("/login", methods=["GET", "POST"])
Just a holdover from initial build out, split them up https://github.com/dod-ccpo/atst/pull/1789/commits/1ef7e93f4dc42a52865f5d0614663a6366ec8c4b

2020-09-15 19:31 UTC, graham-dds approved these changes

2020-09-16 14:25 UTC, merged