[AT-5518] fix(download Task Order PDF):
dod-ccpo/atst pull request #1809
Opened 2020-09-17 21:42 UTC by steve-atat

[Jira](https://ccpo.atlassian.net/browse/AT-5518)

Paired with @graham-dds  on this

- import TaskOrderView fragment with context
- pass 'pdf_download_url' value
to TaskOrder view template

2020-09-18 15:19 UTC, tomdds approved these changes

2020-09-21 16:11 UTC, tomdds requested changes
Looks like this is failing a test in CI, `test_view_task_order_draft` since that explicitly sets `None` as the value of `task_order.pdf`. Since you technically can't create a draft TO _without_ uploading a task order, I think it makes sense to update the draft test to stub in values for the pdf properties and patch `app.csp.files.generate_download_link`

2020-09-22 19:46 UTC, dandds approved these changes
LGTM!

2020-09-22 20:06 UTC, carleton-dds approved these changes

2020-09-22 21:35 UTC, tomdds approved these changes

2020-09-22 22:03 UTC, merged