[AT-4977] Enumerate Postgres user perms in create_database_user.py.
dod-ccpo/atst pull request #1821
Opened 2020-09-22 12:06 UTC by dandds

This change explicitly lists the database permissions that the application's database user requires for the database. It also deletes some of the SQL that's no longer necessary because of the order the database bootstrapping scripts are now run in.

I tested this by running the database bootstrapping scripts against a fresh Azure Postgres instance. Everything ran successfully. I connected to the new database instance as the new ATAT user via psql and was able to SELECT, INSERT, UPDATE, etc.

2020-09-22 16:51 UTC, mikepw approved these changes

2020-09-22 16:51 UTC, mikepw requested changes
can you escape the the params so ansible works, like \"{dbname}\" and \"{username}\" ?

2020-09-22 20:50 UTC, carleton-dds approved these changes
Tested locally, LGTM

2020-09-23 09:55 UTC, mikepw approved these changes

2020-09-23 10:33 UTC, merged