[AT-5529] Generate maintenance page
dod-ccpo/atst pull request #1822
Opened 2020-09-22 19:00 UTC by okaycj-atat

This PR will provide a script to generate an "Under Maintenance" page using the currently existing flask/jinja2 template system.  

[AT-5529](https://ccpo.atlassian.net/browse/AT-5529)

Open Questions:
- How will this get deployed?  
- Are there any limitations to the html service for this page?  Can is serve local assets?

Todo:
- Add argparse and command line help.
- Copy assets referenced in the css file.

2020-09-23 15:39 UTC, dandds reviewed
If I'm reading correctly, it looks like you're extracting all the HTML, CSS, and JS files and copying them to a known location. That's a good start, but I think we'll need the CSS and JS added to the HTML file. That might be something you can do with pyquery.

2020-09-23 18:54 UTC, okaycj-atat commented
> If I'm reading correctly, it looks like you're extracting all the HTML, CSS, and JS files and copying them to a known location. That's a good start, but I think we'll need the CSS and JS added to the HTML file. That might be something you can do with pyquery.

I had a quick talk with @jesse-dds about the limitations of the service where the "Under Maintenance" page is going.  You're correct.  I have another concern about handling binaries.  The docs suggest encoding them as base64 and adding them to the html file.  There's a bit more work todo before I am in the ball park.

2020-10-01 17:15 UTC, graham-dds reviewed
Looks like a good start. I have few things I was hoping you could address before I do a more in-depth review:
1. It looks like you did a reformat of the `README` in addition adding the `How to generate the Under Maintenance page` section. Could you remove those formatting changes from this PR? Having standard markdown formatting could be useful, but we'd probably want to apply those changes similarly to how we handled #1761 and  #1832 .
2. I noticed that `pyquery` isn't in our `pyproject.toml`. I does look like we use it for load testing, but it it's `pip` installed in a Dockerfile in that context. We _do_ have BeautifulSoup in our `pyproject.toml` though (which we use for JS tests), and that seems like it could be used for the needs of this script. Do you think it would be possible to use BeautifulSoup instead of adding another dependency? Alternatively, if it does make sense to add `pyquery` to our dev dependencies to facilitate load testing development, maybe that could happen in this PR.
3. With the above in mind: Would it be good to include at least one test for this script, just to assert that `a page successfully is generated` ? Maybe we could also assert that the page is <= 1 megabyte, like you do in that `print` statement.

2020-10-01 18:41 UTC, tomdds requested changes

2020-10-01 18:41 UTC, tomdds commented on script/generate_under_maintenance.py
> +from pyquery import PyQuery as pq
pyquery isn't currently part of this project's dependencies, you'll want to add it as at least a dev dependecy

2020-10-01 18:41 UTC, tomdds commented on script/generate_under_maintenance.py
> +            d("head").after(f"<style type='text/css'>{css_str}</style>")
You probably want `append` and not `after` here. `after` is going to result in 2 problems:
1) The style tags will be inserted between `head` and `body`
2) The style tags will be inserted in the opposite order of their original declaration because you're iterating front to back, but prepending with `after`

2020-10-01 18:41 UTC, tomdds commented on README.md
> +7. Finally, ATAT will check for the presence of environment variables matching all known config values. If a matching environment variable exists, its value will override whatever value was previousl
This block is supposed to be indented, not sure if it was a formatting tool or what, but 4, 5, & 6 are a sub-list of 3.

2020-10-01 20:21 UTC, okaycj-atat commented on script/generate_under_maintenance.py
> +    html_file = args.output / "index.html"
I like pathlib, but I don't mind going for the clearer option.

2020-10-01 20:23 UTC, okaycj-atat commented on script/generate_under_maintenance.py
> +from pyquery import PyQuery as pq
@graham-dds has raised the point that BeautifulSoup is already a dependency of this project.  I have never used this library before.  Should I opt for this package instead?

2020-10-01 20:24 UTC, okaycj-atat commented on script/generate_under_maintenance.py
> +            d("head").after(f"<style type='text/css'>{css_str}</style>")
I should have checked the html file in a text editor and not in chrome.

2020-10-01 20:32 UTC, okaycj-atat commented on README.md
> +7. Finally, ATAT will check for the presence of environment variables matching all known config values. If a matching environment variable exists, its value will override whatever value was previousl
This is embarrassing!  Also, this is something @graham-dds pointed out in a comment above.  I'll make sure to get this fixed.

2020-10-01 20:36 UTC, tomdds commented on script/generate_under_maintenance.py
> +from pyquery import PyQuery as pq
👍  I don't think there's anything BeautifulSoup can't also do here. I'd go with existing dependencies rather than adding new ones when possible.

2020-10-02 10:51 UTC, dandds reviewed
This is neat! I hope it was fun to write. I have a small comment and question.

When I run the script, the HTML file produced can't seem to load the fonts.

<img width="1481" alt="Screen Shot 2020-10-02 at 6 51 16 AM" src="https://user-images.githubusercontent.com/38955503/94915893-ad4e2400-047b-11eb-8375-0f63b703baaa.png">

2020-10-02 10:51 UTC, dandds commented on script/generate_under_maintenance.py
> +                css_str = re.sub(r"/\*.*?\*/", "", fh.read().strip())
If you want this to match CSS comments spanning multiple lines, like

```css
/*
* comment
* across
* lines
*/
```
then I'm pretty sure you need to add a regex flag:

```python
css_str = re.sub(r"/\*.*?\*/", "", fh.read().strip(), flags=re.S)
```
https://docs.python.org/3/library/re.html#re.S

Find/replaces make me nervous because it's very easy to delete patterns in text you didn't anticipate, but it's probably fine as long as we vet the output really well.

2020-10-02 10:51 UTC, dandds commented on templates/under_maintenance.html
> +<body>
Maybe I missed it, but is there some reason this template can't use the base template?

2020-10-02 13:25 UTC, okaycj-atat commented on templates/under_maintenance.html
> +<body>
The initial iteration of this used the public base template.  The public base template comes with the two banners at the top of the page and that is no longer a requirement.  I feel that to use a base template I would have to refactor a few templates.  Is that something I should dig into?

2020-10-02 13:28 UTC, okaycj-atat commented
> When I run the script, the HTML file produced can't seem to load the fonts.

@dandds Yup!  The cache busting got me!  I'll need to change how the whitelist works.

2020-10-02 13:32 UTC, dandds commented on templates/under_maintenance.html
> +<body>
It seems like it could be easy to forget to update all the boilerplate in `<head>` across multiple templates if it changes; maybe pull that shared markup into a partial, or create a more basic base template for both (`base_base.html` 😁 ).

2020-10-02 13:33 UTC, okaycj-atat commented on script/generate_under_maintenance.py
> +                css_str = re.sub(r"/\*.*?\*/", "", fh.read().strip())
I assume when we get the design, this script will need some edits.  I am sure I've missed some corner cases.  About the new lines, I am assuming there aren't any.  The CSS file is minimized and the contents of the file should all be on one line.

2020-10-02 13:33 UTC, okaycj-atat commented on script/generate_under_maintenance.py
> +                css_str = re.sub(r"/\*.*?\*/", "", fh.read().strip())
That being said, I will make this change.

2020-10-05 17:18 UTC, tomdds approved these changes

2020-10-05 19:27 UTC, graham-dds reviewed
Looking better! A few more things:
- could we add `#! .venv/bin/python` to the top of the script so that we can run it like `script/generate_under_maintenance.py`?
- I noticed [this commit](https://github.com/dod-ccpo/atst/pull/1822/commits/30fe133b3c271944ae5eac72fda66211ae83edef). Is there a reason you decided not to go with pathlib? It might remove the need for some of the little utility functions that you've defined in the script. For example, `file_ext()` could be replaced by the [.suffix](https://docs.python.org/3.7/library/pathlib.html#pathlib.PurePath.suffix) property of a Pathlib object. It would also _feel_ better to use [`relative_to`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to) rather than using `urllib.parse` when we aren't really dealing with URLs.
- I'm getting the same error that @dandds [was earlier](https://github.com/dod-ccpo/atst/pull/1822#pullrequestreview-501030004) about fonts:
![image](https://user-images.githubusercontent.com/54586407/95116615-4ba8e680-0715-11eb-88d5-5ea857c65948.png)
- The code in the `if __name__ == "__main__":` block seems to be responsible for a lot in this script. Do you think it would be worth breaking that section of the script into smaller functions with fewer responsibilities, then composing them in some `main()` function? I noticed that some of the comments above sections in the script (e.g. `# render template`,  `# encode images`, `# add css to html`) seem like natural places to split the script into smaller functions.
- Did you consider writing a small test or two like I pointed out in my last review?

I also have a question about template inheritance / extending, but I'll try to catch up with you about this in a Zoom call

2020-10-05 19:27 UTC, graham-dds commented on templates/base_head.html
> +</html>
Missing newline here

2020-10-06 18:56 UTC, okaycj-atat commented on script/generate_under_maintenance.py
> +sys.path.append(parent_dir)
This something another review requested.  I am going to leave at is, unless you feel strongly.

2020-10-06 19:00 UTC, okaycj-atat commented
> * could we add `#! .venv/bin/python` to the top of the script so that we can run it like `script/generate_under_maintenance.py`?

I have added a shebang to the script.  Thank you.

2020-10-06 19:01 UTC, okaycj-atat commented
> * I noticed [this commit](https://github.com/dod-ccpo/atst/pull/1822/commits/30fe133b3c271944ae5eac72fda66211ae83edef). Is there a reason you decided not to go with pathlib? It might remove the need for some of the little utility functions that you've defined in the script. For example, `file_ext()` could be replaced by the [.suffix](https://docs.python.org/3.7/library/pathlib.html#pathlib.PurePath.suffix) property of a Pathlib object. It would also _feel_ better to use [`relative_to`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to) rather than using `urllib.parse` when we aren't really dealing with URLs.

Another reviewer found `pathlib` to be confusing.  It was removed.

2020-10-06 19:06 UTC, okaycj-atat commented
> * I'm getting the same error that @dandds [was earlier](https://github.com/dod-ccpo/atst/pull/1822#pullrequestreview-501030004) about fonts:

Yup, I keep finding corner cases when it comes to assets found in css.  The whole matched string will change depending on how the local development site is deployed (minified vs not).  I am now using the regex grouping mechanism.  This give me access to the whole matches string and a group within it.  I am can now assume less.

2020-10-06 19:07 UTC, okaycj-atat commented
> * The code in the `if __name__ == "__main__":` block seems to be responsible for a lot in this script. Do you think it would be worth breaking that section of the script into smaller functions with fewer responsibilities, then composing them in some `main()` function? I noticed that some of the comments above sections in the script (e.g. `# render template`,  `# encode images`, `# add css to html`) seem like natural places to split the script into smaller functions.

I have refactored the script to now use a main() function. Thank you.

2020-10-06 19:30 UTC, okaycj-atat commented
> * Did you consider writing a small test or two like I pointed out in my last review?

My apologies and thank you for reminding me to do this.  It slipped my mind.  There is now a test to validate the html file size.

2020-10-07 17:07 UTC, graham-dds approved these changes
:shipit: 

Nice! Thanks for hanging with me for all the change requests. There a few more tweaks that _could_ be made, but they can be addressed when we modify the output of the script to align with Think Co. designs.

2020-10-08 14:30 UTC, merged