Fix database and saml overlay templates
dod-ccpo/atst pull request #1874
Opened 2020-10-15 19:48 UTC by jesse-dds

Fixes two issues that occurred during the 5th dry run.

2020-10-15 19:51 UTC, carleton-dds commented
Can we also fix that line in `Kustomization.yml`? https://github.com/dod-ccpo/atst/blob/710f20266f5e921ad1ea4e9743a133604bd09d00/ansible/roles/k8s/tasks/templates/kustomization.yml#L3

2020-10-15 20:51 UTC, carleton-dds requested changes
Can we also fix that line in `Kustomization.yml`? I think it should just be `../../azure/`

 https://github.com/dod-ccpo/atst/blob/710f20266f5e921ad1ea4e9743a133604bd09d00/ansible/roles/k8s/tasks/templates/kustomization.yml#L3

2020-10-23 15:25 UTC, jeffdeville-pw approved these changes

2020-10-23 19:54 UTC, carleton-dds approved these changes

2020-10-23 19:55 UTC, merged