[AT-5531] Script SAML provider creation
dod-ccpo/atst pull request #1910
Opened 2020-10-29 13:44 UTC by jesse-dds

Scripts the process of SAML provider creation described in this [document](https://github.com/dod-ccpo/atst/blob/staging/docs/SAMLIDP.md). It accomplishes "A development IdP is automatically created for non-prod environments" of this [ticket](https://ccpo.atlassian.net/browse/AT-5449).

This script primarily:
- Creates a new app registration
- Enables SAML single sign on
- Adds a self-signed certificate
- Adds several users from a `user_service_principals.txt` files to the newly created app registration

2020-10-29 16:27 UTC, graham-dds requested changes
Do you think we could break the `main()` function up into sub-functions? It seems like places where you included comments to explain what the function is doing at that point in the script (`# Authenticate with the provided service principle.`, `# Create a new app registration from a template.`, etc) could be good places to split things up. This will make the script easier to follow and test.

2020-10-29 17:02 UTC, graham-dds commented on ops/create-saml-idp.py
> +        except requests.HTTPError:
This while loop makes me a bit nervous. Could we maybe only retry on certain HTTP errors? I think the only error that tells us the provisioning _might_ still be running is a 401, right? And with that, maybe we add a timeout via a max number of iterations for this loop so we're not stuck here forever?

2020-10-29 17:02 UTC, graham-dds commented on ops/create-saml-idp.py
> +            x509.SubjectAlternativeName([x509.DNSName("localhost")]),
is DNSName always going to be `localhost`?

2020-10-30 12:59 UTC, carleton-dds commented on ops/create-saml-idp.py
> +        "Content-Type": "application/json",
Instead of `localhost` These need to be the FQDN of the new site. `dryrun.atat.dev`

2020-11-17 21:32 UTC, tomdds commented on ops/create-saml-idp.py
> +    # Authenticate with the provided service principle.
Not going to use this util because it assumes a configured app/csp and this script runs entirely in the terraform/ansible context, so the ATAT app isn't available

2020-11-18 16:15 UTC, tomdds commented on ops/create-saml-idp.py
> +            x509.SubjectAlternativeName([x509.DNSName("localhost")]),
Added a comment about it, we're generating this cert for signing SAML payloads, so the DNS name is actually irrelevant since we don't use it for TLS or anything, just basic crypto

2020-11-23 16:09 UTC, graham-dds approved these changes
Looks good! I left a few more questions and comments, but nothing stopping an approval.

Also, I noticed a few places were we provide a `"Content-Type": "application/json",` header when posting / patching json. I don't think this is necessary if you're using the `json` kwarg, but I guess it doesn't hurt to keep it.

2020-11-23 16:09 UTC, graham-dds commented on reset_db.sh
> +#!/bin/bash
Is this file meant to be in this PR? I'm not sure how it relates to the SAML stuff.

2020-11-23 16:09 UTC, graham-dds commented on ops/create-saml-idp.py
> +        "appRoleId": "18d14569-c3bd-439b-9a66-3a2aee01d14f",
Is there any documentation we can point to for this magic UUID?

2020-11-24 20:46 UTC, tomdds commented on reset_db.sh
> +#!/bin/bash
oh oops, not sure how this got caught up

2020-11-24 21:07 UTC, tomdds commented on ops/create-saml-idp.py
> +        "appRoleId": "18d14569-c3bd-439b-9a66-3a2aee01d14f",
The only place I'm seeing it is in an example in their docs: https://docs.microsoft.com/en-us/graph/application-proxy-configure-api?tabs=http

@jesse-dds any ideas?

2020-12-01 17:06 UTC, carleton-dds reviewed
This all looks good 🙌. 2 quick changes would be great though:

1. Can you log the application ID of the newly created app?  It will make debugging any potential issues quicker
2. The script assumes`user_service_principals.txt` exists in the same directory. Can you add a check for that when the script runs, as well as some detail, perhaps in the help text of the script, that the file must be present and contain one user_object_id per line?

2020-12-03 14:44 UTC, carleton-dds approved these changes

2020-12-03 17:18 UTC, merged