[AT-5555] Saml helper xss attack
dod-ccpo/atst pull request #1953
Opened 2020-11-11 19:38 UTC by okaycj-atat

This PR simply wraps next parameter in an existing parameters check.  

[Jira](https://ccpo.atlassian.net/browse/AT-5555)

2020-11-12 18:50 UTC, tomdds requested changes
Just a small test update, otherwise looks good.

2020-11-12 18:50 UTC, tomdds commented on tests/routes/test_saml_helpers.py
> +    assert "next_param" not in qsp
Can you add an affirmative test for this as well? Use a next value like `/home`, which should validate correctly.

2020-11-16 19:58 UTC, tomdds approved these changes
Once you fix the formatting issues, this looks good!

2020-11-16 22:03 UTC, carleton-dds approved these changes

2020-11-17 18:02 UTC, merged